// --- LIBRERIE NECESSARIE ---
#include "arduino_secrets.h"  // Contiene le password e i dati sensibili (es. password del WiFi)
#include <arduino-timer.h>    // Permette di eseguire azioni a intervalli regolari senza bloccare il codice con delay()
#include <DHT.h>              // Libreria per gestire il sensore di temperatura e umidità DHT
#include <HTTPClient.h>       // Libreria per effettuare richieste HTTP (es. inviare dati al web)
#include <WiFiClientSecure.h> // Necessaria per le connessioni sicure (HTTPS), come quelle richieste da Google

// --- CONFIGURAZIONE SENSORE DHT ---
#define DHTPIN 23         // Il sensore è collegato al pin digitale 23
#define DHTTYPE DHT11     // Specifica il modello del sensore (DHT11)
DHT dht(DHTPIN, DHTTYPE); // Crea l'oggetto 'dht' per comunicare col sensore

#define LIGHTPIN 34

// Crea un timer per gestire l'intervallo di lettura dei dati
auto timer = timer_create_default();

/*
  Sketch generated by the Arduino IoT Cloud Thing "Bedroom temp hum"
  https://create.arduino.cc/cloud/things/6a48c2ed-3f2b-41b7-a6fa-c173eb766b13

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  float Humidity;
  float Temperature;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/
#include "thingProperties.h"

int tDelay = 60000; // Tempo di attesa tra una lettura e l'altra (60.000 millisecondi = 1 minuto)

// URL dello script di Google che riceverà i dati

// --- FUNZIONE PER INVIARE DATI A GOOGLE SHEETS ---
void sendToGoogleSheets()
{
  // Controlla che la scheda sia effettivamente connessa a Internet
  if (WiFi.status() == WL_CONNECTED)
  {
    // Crea un client "sicuro" perché Google richiede una connessione HTTPS criptata
    WiFiClientSecure *client = new WiFiClientSecure;
    client->setInsecure(); // Salta la verifica del certificato SSL (utile e veloce per questi piccoli progetti)

    HTTPClient https;
    https.setTimeout(5000); // Imposta un tempo massimo di attesa per la risposta di 15 secondi

    // Costruisce l'URL finale aggiungendo i valori di temperatura e umidità letti dal sensore
    // Esempio: .../exec?temp=25.5&hum=60.0
    String url = GOOGLE_SCRIPT_URL + "?temp=" + String(Temperature) + "&hum=" + String(Humidity) + "&light=" + String(Light);

    // Stampa sul Monitor Seriale del PC cosa stiamo per inviare (utile per fare debug)
    Serial.print("Invio dati a Google Sheets -> Temperature: ");
    Serial.print(Temperature);
    Serial.print(" - Humidity: ");
    Serial.print(Humidity);
    Serial.print(" - Light: ");
    Serial.println(Light);

    // Avvia la connessione verso l'indirizzo appena costruito
    if (https.begin(*client, url))
    {
      // Fondamentale per Google Scripts: gli script spesso reindirizzano a un'altra pagina (Redirect)
      // Questo comando dice alla scheda di seguire automaticamente il reindirizzamento
      https.setFollowRedirects(HTTPC_STRICT_FOLLOW_REDIRECTS);

      // Effettua la vera e propria richiesta GET
      int httpCode = https.GET();

      // Se il codice è maggiore di 0 significa che il server ha risposto
      if (httpCode > 0)
      {
        String payload = https.getString(); // Legge la risposta inviata da Google
        Serial.println("Risposta Google: " + payload);
      }
      else
      {
        // Altrimenti c'è stato un problema di rete o di connessione
        Serial.println("Errore HTTP: " + https.errorToString(httpCode));
      }
      https.end(); // Chiude la connessione HTTPS per liberare memoria
    }
    else
    {
      Serial.println("Impossibile connettersi a Google");
    }

    // Cancella l'oggetto client per liberare spazio nella RAM della scheda
    delete client;
  }
  else
  {
    Serial.println("WiFi non connesso, invio a Google annullato.");
  }
}

// --- FUNZIONE PER LEGGERE IL SENSORE ---
// Questa funzione viene chiamata dal 'timer' ogni 60 secondi
bool readDHT(void *)
{
  // Legge l'umidità e la temperatura dal sensore e le salva nelle variabili globali
  // (Queste variabili sono probabilmente definite nel file "thingProperties.h" per l'Arduino Cloud)
  Humidity = dht.readHumidity();
  Temperature = dht.readTemperature();
  Light = analogRead(LIGHTPIN);

  // Controlla se la lettura è fallita (isnan = is not a number)
  if (isnan(Humidity) || isnan(Temperature))
  {
    Serial.println(F("Failed to read from DHT sensor!"));
    return true; // Ritorna 'true' per dire al timer di riprovare al prossimo giro
  }

  // Se la lettura è valida, chiama la funzione per inviare i dati a Google
  sendToGoogleSheets();

  return true; // Ritorna 'true' per mantenere il timer attivo
}

// --- FUNZIONE DI AVVIO (Eseguita una sola volta) ---
void setup()
{
  Serial.begin(9600); // Inizia la comunicazione con il Monitor Seriale
  delay(1500);        // Aspetta un secondo e mezzo per dare tempo alla seriale di avviarsi

  pinMode(LIGHTPIN, INPUT);

  initProperties(); // Inizializza le variabili legate ad Arduino IoT Cloud

  // Avvia la connessione al Cloud e al WiFi utilizzando le credenziali salvate in arduino_secrets.h
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);

  setDebugMessageLevel(25);      // Imposta il livello di dettaglio dei messaggi di errore (2 = abbastanza dettagliato)
  ArduinoCloud.printDebugInfo(); // Stampa le info di debug della connessione Cloud

  dht.begin(); // Accende/Inizializza il sensore di temperatura

  // Configura il timer: ogni 'tDelay' (60 secondi), esegui la funzione 'readDHT'
  timer.every(tDelay, readDHT);
}

// --- CICLO PRINCIPALE (Eseguito all'infinito) ---
void loop()
{
  ArduinoCloud.update(); // Mantiene viva la connessione con Arduino Cloud e aggiorna i dati in tempo reale
  timer.tick();          // Fa avanzare il tempo per il nostro timer, permettendogli di "scattare" ogni minuto
}