// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "46c859c8-9911-461a-bf43-cebe10896ab1";

String GOOGLE_SCRIPT_URL = "https://script.google.com/macros/s/AKfycbxylHz68UalDPag04V3WzylNKI1JQU8xhftzpZ32xO6D6ufVIhpFReo90dHFvGPXaoD/exec";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password


float Humidity;
float Temperature;
int Light;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(Humidity, READ, 60 * SECONDS, NULL);
  ArduinoCloud.addProperty(Temperature, READ, 60 * SECONDS, NULL);
  ArduinoCloud.addProperty(Light, READ, 60 * SECONDS, NULL);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
